GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/token/validar/f78f4005c5ddf3137a8fca1e7ba9fff2

###

POST http://localhost:3000/api/users/create 
Content-Type: application/json

{
"cedula":"1111111111",
"nombre":"aaaa",
"apellido":"bbbb",
"correo":"felicita59@ethereal.email",
"password":"1234"
}



###

POST http://localhost:3000/api/token
Content-Type: application/json

{
"correo":"felicita59@ethereal.email",
"password":"1234"
}