GET http://localhost:3000/api/users 

###
GET http://localhost:3000/api/token/validar/d4ea0a224a399c7fe1bdbc792b2036d6

###

POST http://localhost:3000/api/users/create 
Content-Type: application/json

{
"cedula":"1111111111",
"nombre":"aaaa",
"apellido":"bbbb",
"correo":"aaaaaa@gmail.com",
"password":"1234"
}



###

POST http://localhost:3000/api/token
Content-Type: application/json

{
"correo":"aaaaaa@gmail.com",
"password":"1234"
}