GET http://localhost:3000/api/users 

###

POST http://localhost:3000/api/users/create 
Content-Type: application/json

{
"cedula":"1111111111",
"nombre":"aaaa",
"apellido":"bbbb",
"correo":"aaaaaa@gmail.com",
"password":"1234"
}

###
GET http://localhost:3000/api/token/validar/03e22b296e7a01bc84240838c3b5a71f